FROM bcgovimages/aries-cloudagent:py36-1.15-0_0.5.6

RUN echo "Just pulling the image from Docker Hub"

RUN pip3 install -e "git+https://github.com/nrempel/aries-cloudagent-python.git@master#egg=aries-cloudagent"
