FROM bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1

RUN echo "Just pulling the image from Docker Hub"
# FROM bcgovimages/von-image:py36-1.12-0

RUN pip3 install -e "git+https://github.com/nrempel/aries-cloudagent-python.git@master#egg=aries-cloudagent"
