# Generated by Django 2.2.2 on 2019-10-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiw_book', '0003_auto_20190420_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField()),
                ('state', models.TextField()),
            ],
        ),
    ]