---
kind: Template
apiVersion: v1
metadata:
  name: ${NAME}
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_GROUP}
        app-group: ${APP_GROUP}
    spec:
      ports:
        - name: ${NAME}-admin
          port: ${{INDY_ADMIN_PORT}}
          protocol: TCP
          targetPort: ${{INDY_ADMIN_PORT}}
        - name: ${NAME}-agent
          port: ${{INDY_AGENT_PORT}}
          protocol: TCP
          targetPort: ${{INDY_AGENT_PORT}}
      selector:
        name: ${NAME}

  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_GROUP}
        app-group: ${APP_GROUP}
    spec:
      host: ${APPLICATION_DOMAIN}
      port:
        targetPort: ${NAME}-agent
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}
        weight: 100

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_GROUP}
        app-group: ${APP_GROUP}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${PERSISTENT_VOLUME_SIZE}
      storageClassName: ${PERSISTENT_VOLUME_CLASS}

  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_GROUP}
        app-group: ${APP_GROUP}
    stringData:
      seed: ${WALLET_SEED}
    type: Opaque

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_GROUP}
        app-group: ${APP_GROUP}
    spec:
      replicas: 1
      selector:
        name: ${NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          name: ${NAME}
          labels:
            name: ${NAME}
            app: ${APP_GROUP}
            app-group: ${APP_GROUP}
        spec:
          containers:
            - name: ${NAME}
              command:
                - bash
                - -c
                - aca-py
                  start
                  -it http 0.0.0.0 ${AGENT_PORT}
                  -ot http
                  --admin 0.0.0.0 ${ADMIN_PORT}
                  -e "${SITE_URL}"
                  --wallet-type indy
                  --seed "${INDY_WALLET_SEED}"
                  --genesis-url "${GENESIS_URL}"
                  --auto-accept-invites
                  --auto-accept-requests
                  --admin-insecure-mode
                  --label "${LABEL}"
              env:
                - name: ADMIN_PORT
                  value: ${INDY_ADMIN_PORT}
                - name: AGENT_PORT
                  value: ${INDY_AGENT_PORT}  
                - name: INDY_WALLET_SEED
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: seed            
                - name: GENESIS_URL
                  value: ${GENESIS_FILE_URL}
                - name: SITE_URL
                  value: ${AGENT_URL}
                - name: WEBHOOK_URL
                  value: ${WEBHOOK_URL}
                - name: LABEL
                  value: ${DISPLAY_LABEL}
              image: " "
              ports:
                - containerPort: ${{INDY_ADMIN_PORT}}
                  protocol: TCP
                - containerPort: ${{INDY_AGENT_PORT}}
                  protocol: TCP
              readinessProbe:
                timeoutSeconds: 30
                initialDelaySeconds: 3
                httpGet:
                  path: "/"
                  port: ${{INDY_AGENT_PORT}}
              livenessProbe:
                timeoutSeconds: 30
                initialDelaySeconds: 300
                httpGet:
                  path: "/"
                  port: ${{INDY_AGENT_PORT}}
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - name: ${NAME}-data
                  mountPath: ${MOUNT_PATH}
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: ${NAME}-data
              persistentVolumeClaim:
                claimName: ${NAME}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}:${TAG_NAME}
              namespace: ${IMAGE_NAMESPACE}

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all the objects defined in this template.
    required: true
    value: iiw-book-agent
  - name: APP_GROUP
    displayName: App Group
    description: Used to group components together.
    required: true
    value: iiw-book
  - name: APPLICATION_DOMAIN
    displayName: Application Hostname
    description: The exposed hostname that will route to the service, if left blank a value will be defaulted.
    required: false
    value: iiwbook-agent.vonx.io
  - name: IMAGE_NAMESPACE
    displayName: Namespace containing application images.
    required: true
    value: devex-von-image-tools
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod.
    required: true
    value: dev
  - name: INDY_ADMIN_PORT
    displayName: Admin Port
    description: The admin port on which the service will listen.
    required: true
    value: "4000"
  - name: INDY_AGENT_PORT
    displayName: Agent Port
    description: The agent port on which the service will listen.
    required: true
    value: "11000"
  - name: WALLET_SEED
    displayName: Indy Wallet Seed
    description: The Seed used for the indy wallet.  Needs to be base64 encoded.
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: AGENT_URL
    displayName: Site URL
    description: The URL for the site
    required: true
    value: https://iiwbook-agent.vonx.io
  - name: WEBHOOK_URL
    displayName: Webhook URL
    description: The webhook endpoint
    required: true
    value: http://iiw-book-service:8080/webhooks
  - name: GENESIS_FILE_URL
    displayName: Genesis File URL
    description: The URL from which the genesis file can be downloaded.
    required: true
    value: https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_sandbox_genesis
  - name: DISPLAY_LABEL
    displayName: Display Label
    description: Display label
    required: true
    value: ConfBook
  - name: MOUNT_PATH
    displayName: Mount Path
    description: The path to mount the persistent volume.
    required: true
    value: /home/indy/.indy_client/wallet
  - name: PERSISTENT_VOLUME_SIZE
    displayName: Persistent Volume Size
    description: The size of the persistent volume , e.g. 512Mi, 1Gi, 2Gi.
    required: true
    value: 5Gi
  - name: PERSISTENT_VOLUME_CLASS
    displayName: Persistent Volume Class name
    description: The class of the volume; gluster-file, gluster-block, gluster-file-db
    required: false
    value: gluster-file-db
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 250m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 1Gi
