---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${NAME}
objects:
# - kind: ExternalNetwork
#   apiVersion: security.devops.gov.bc.ca/v1alpha1
#   metadata:
#     name: ${NAME}
#     network: ${NAME}
#     labels:
#       name: ${NAME}
#       network: ${NAME}
#       app: ${APP_GROUP}
#       app-group: ${APP_GROUP}
#       env: ${TAG_NAME}
#   spec:
#     description: |
#       Define the network parameters for accessing smtp server
#     entries:
#       - ${SMTP_EMAIL_HOST}
#     servicePorts:
#       - tcp/25
# - kind: NetworkSecurityPolicy
#   apiVersion: security.devops.gov.bc.ca/v1alpha1
#   metadata:
#     name: ${NAME}
#     labels:
#       name: ${NAME}
#       env: ${TAG_NAME}
#       app: ${APP_GROUP}
#       app-group: ${APP_GROUP}
#   spec:
#     description: Allow service to access the database and agent
#     source:
#       - - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
#         - role=${ROLE}
#         - app=${APP_GROUP}
#         - env=${TAG_NAME}
#     destination:
#       - - ext:name=${NAME}
#       - - role=db
#         - app=${APP_GROUP}
#         - env=${TAG_NAME}
#         - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
#       - - role=agent
#         - app=${APP_GROUP}
#         - env=${TAG_NAME}
#         - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: ${NAME}-allow-ingress
    labels:
      name: ${NAME}-allow-ingress
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
      role: ${ROLE}
      env: ${TAG_NAME}
  spec:
    description: |
      Allow traffic from routes into the ${ROLE} container(s).
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                network.openshift.io/policy-group: ingress
    podSelector:
      matchLabels:
        role: ${ROLE}
        app: ${APP_GROUP}
        env: ${TAG_NAME}
    policyTypes:
      - Ingress
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: ${NAME}
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      env: ${TAG_NAME}
  spec:
    description: Allow the agent to access the service.
    ingress:
      - from:
        - podSelector:
            matchLabels:
              role: ${AGENT_ROLE}
              app: ${APP_GROUP}
              env: ${TAG_NAME}
          namespaceSelector:
            matchLabels:
              name: ${NAMESPACE_NAME}
              environment: ${TAG_NAME}
        ports:
          - protocol: TCP
            port: ${{PORT}}
    podSelector:
      matchLabels:
        role: ${ROLE}
        app: ${APP_GROUP}
        env: ${TAG_NAME}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
      role: ${ROLE}
      env: ${TAG_NAME}
  spec:
    ports:
    - name: ${NAME}
      port: ${{PORT}}
      protocol: TCP
      targetPort: ${{PORT}}
    selector:
      name: ${NAME}

- kind: Route
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
      role: ${ROLE}
      env: ${TAG_NAME}
      certbot-managed: ${CERTBOT_MANAGED_ROUTE}
  spec:
    host: ${APPLICATION_DOMAIN}
    port:
      targetPort: ${NAME}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}
      weight: 100

- kind: Route
  apiVersion: v1
  metadata:
    name: ${CONF_BOOK_ROUTE_NAME}
    labels:
      name: ${CONF_BOOK_ROUTE_NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
      role: ${ROLE}
      env: ${TAG_NAME}
      certbot-managed: ${CERTBOT_MANAGED_ROUTE}
  spec:
    host: ${CONF_BOOK_APPLICATION_DOMAIN}
    port:
      targetPort: ${NAME}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}
      weight: 100

- kind: Secret
  apiVersion: v1
  metadata:
    name: ${NAME}-email-host
    labels:
      app: ${APP_GROUP}
      name: ${NAME}
      app-group: ${APP_GROUP}
      role: ${ROLE}
      env: ${TAG_NAME}
  stringData:
    email-host: ${SMTP_EMAIL_HOST}
  type: Opaque

- kind: Secret
  apiVersion: v1
  metadata:
    name: ${NAME}-verifier-did
    labels:
      app: ${APP_GROUP}
      name: ${NAME}
      app-group: ${APP_GROUP}
      role: ${ROLE}
      env: ${TAG_NAME}
  stringData:
    verifier-did: ${INDY_EMAIL_VERIFIER_DID}
  type: Opaque

- kind: Secret
  apiVersion: v1
  metadata:
    name: ${NAME}-staff-emails
    labels:
      app: ${APP_GROUP}
      name: ${NAME}
      app-group: ${APP_GROUP}
      role: ${ROLE}
      env: ${TAG_NAME}
  stringData:
    staff-emails: ${STAFF_EMAILS}
  type: Opaque

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
      role: ${ROLE}
      env: ${TAG_NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        name: ${NAME}
        labels:
          name: ${NAME}
          app: ${APP_GROUP}
          app-group: ${APP_GROUP}
          role: ${ROLE}
          env: ${TAG_NAME}
      spec:
        containers:
        - name: ${NAME}
          env:
          - name: PORT
            value: ${PORT}
          - name: INDY_EMAIL_VERIFIER_DID
            valueFrom:
              secretKeyRef:
                name: ${NAME}-verifier-did
                key: verifier-did
          - name: SITE_URL
            value: ${SITE_URL}
          - name: AGENT_URL
            value: ${AGENT_URL}
          - name: DEBUG
            value: ${DEBUG}
          - name: AGENT_ADMIN_API_KEY
            valueFrom:
              secretKeyRef:
                name: ${AGENT_SERVICE_NAME}-api
                key: admin-api-key
          - name: DB_NAME
            value: ${DATABASE_NAME}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${DATABASE_SERVICE_NAME}
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${DATABASE_SERVICE_NAME}
          - name: DB_PORT
            value: ${DATABASE_PORT}
          - name: DB_HOST
            value: ${DATABASE_SERVICE_NAME}
          - name: EMAIL_HOST
            valueFrom:
              secretKeyRef:
                name: ${NAME}-email-host
                key: email-host
          - name: EMAIL_PORT
            value: ${EMAIL_PORT}
          - name: EMAIL_USE_SSL
            value: ${EMAIL_USE_SSL}
          - name: STAFF_EMAILS
            valueFrom:
              secretKeyRef:
                name: ${NAME}-staff-emails
                key: staff-emails
          - name: APP_MODULE
            value: ${APP_MODULE}
          - name: APP_CONFIG
            value: ${APP_CONFIG}
          - name: WEB_CONCURRENCY
            value: ${WEB_CONCURRENCY}
          - name: CONFERENCE_OPTIONS
            value: ${CONFERENCE_OPTIONS}
          image: " "
          ports:
          - containerPort: ${{PORT}}
            protocol: TCP
          readinessProbe:
            timeoutSeconds: 30
            initialDelaySeconds: 3
            httpGet:
              path: "/"
              port: ${{PORT}}
          livenessProbe:
            timeoutSeconds: 30
            initialDelaySeconds: 300
            httpGet:
              path: "/"
              port: ${{PORT}}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:${TAG_NAME}
          namespace: ${IMAGE_NAMESPACE}

parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all the objects defined in this template.
  required: true
  value: iiw-book-service
- name: APP_GROUP
  displayName: App Group
  description: Used to group components together.
  required: true
  value: iiw-book
- name: NAMESPACE_NAME
  displayName: NameSpace name
  description: name of the project namespace
  required: true
  value: myproject
- name: ROLE
  displayName: App Role
  description: used to divide componenets into specific roles
  required: true
  value: service
- name: AGENT_ROLE
  displayName: Agent Role
  description: The role name of the agent service
  required: true
  value: agent
- name: AGENT_SERVICE_NAME
  displayName: Agent Service Name
  description: The name of the agent service
  required: true
  value: iiw-book-agent
- name: APPLICATION_DOMAIN
  displayName: Application Hostname
  description: The exposed hostname that will route to the service, if left blank a value will be defaulted.
  required: false
  value: iiwbook.vonx.io
- name: CONF_BOOK_ROUTE_NAME
  displayName: Conference Book Route Name
  description: The name assigned to the conference book route.
  required: true
  value: conf-book-service
- name: CONF_BOOK_APPLICATION_DOMAIN
  displayName: Conference Book  Application Hostname
  description: The exposed hostname that will route to the service, if left blank a value will be defaulted.
  required: false
  value: confbook.vonx.io
- name: CERTBOT_MANAGED_ROUTE
  displayName: Certbot Managed Route
  description: Flag indicating whether the routes certificates are managed by CertBot.
  required: true
  value: 'false'
- name: IMAGE_NAMESPACE
  displayName: Namespace containing application images.
  required: true
  value: devex-von-image-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod.
  required: true
  value: dev
- name: APP_MODULE
  displayName: Application Module
  description: Used to run the application with Gunicorn.
  required: true
  value: iiw_book_service.wsgi
- name: APP_CONFIG
  displayName: Gunicorn Config File
  description: option to be passed to gunicorn -c
  required: false
  value: python:iiw_book_service.settings
- name: WEB_CONCURRENCY
  displayName: Web Concurrency
  description: Controls/overrides the number of Gunicorn workers.  This MUST be set to 1 when using a SQLite wallet.
  required: true
  value: "1"
- name: PORT
  displayName: Port
  description: The port on which the service will listen.
  required: true
  value: "8080"
- name: INDY_EMAIL_VERIFIER_DID
  displayName: Indy Email Verifier DID
  description: The did of the email verifier issuer that we trust
  required: true
- name: SITE_URL
  displayName: Site URL
  description: The URL for the site
  required: true
  value: https://iiwbook.vonx.io
- name: AGENT_URL
  displayName: Agent URL
  description: The URL for the agent's admin endpoint.
  required: true
  value: http://iiw-book-agent:4000
- name: DEBUG
  displayName: Debug
  description: Flag to indicate whether the service in running in debug mode.
  required: true
  value: "true"
- name: DATABASE_NAME
  displayName: Database Name
  required: true
  value: iiw-book-db
- name: DATABASE_PORT
  displayName: Database Port
  required: true
  value: "5432"
- name: DATABASE_SERVICE_NAME
  displayName: Database Service Name
  required: true
  value: iiw-book-db
- name: SMTP_EMAIL_HOST
  displayName: Email Host Name
  required: true
- name: EMAIL_PORT
  displayName: Email Port
  required: true
  value: "25"
- name: EMAIL_USE_SSL
  displayName: Email Use SSL
  required: true
  value: "false"
- name: STAFF_EMAILS
  displayName: Emails to send notifications to
  required: true
- name: CONFERENCE_OPTIONS
  displayName: Conference Options
  required: true
  value: "IIW,Hyperledger Global Forum"
- name: CPU_REQUEST
  displayName: Resources CPU Request
  description: The resources CPU request (in cores) for this build.
  required: true
  value: 10m
- name: CPU_LIMIT
  displayName: Resources CPU Limit
  description: The resources CPU limit (in cores) for this build.
  required: true
  value: 250m
- name: MEMORY_REQUEST
  displayName: Resources Memory Request
  description: The resources Memory request (in Mi, Gi, etc) for this build.
  required: true
  value: 10Mi
- name: MEMORY_LIMIT
  displayName: Resources Memory Limit
  description: The resources Memory limit (in Mi, Gi, etc) for this build.
  required: true
  value: 1Gi